---
- name: Restart servers
  hosts: REDHAT
  become: true

  tasks:
  - name: Ping All Servers
    ping:     
  - name: Reboot my servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait till my server will come up online
    wait_for: 
        host: "{{ inventory_hostname }}"
        state: started
        delay: 5
        timeout: 40
    delegate_to: 89.64.120.207